name: Hello World!

on:
  schedule:
    - cron: '25 */08 * * *'
jobs:
  hello-world:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04
    steps:
      - name: print-hello-world
        run: echo "Hello World"